version: '2'
services:
  mqtt-broker:
    container_name: mqtt-broker
    image: emqx/emqx:5.0.15
    restart: unless-stopped
    network_mode: host
    ports:
      - "18083:18083"
      - "1883:1883"
